### PR TITLE
Update vk_icd.h for VK_EXT_directfb_surface extension

### PR DESCRIPTION
**Pull request by caramelli**
This is useful for integration with Vulkan-Loader.

Nicolas Caramelli

### CODE REVIEW

**Comment by oddhack** [comment]
@MarkY-LunarG should changes to vk_icd.h go into another repo like Vulkan-Loader from whence they're propagated here? Probably we should have more docs about what source repo contributes what files to Vulkan-Headers to direct people to the right place.

**Comment by oddhack** [comment]
Also I see the comments in the README are incorrect in that wherever vk_icd.h comes from, it's not Vulkan-Docs.

**Comment by KarenGhavam-lunarG** [comment]
PInging @lenny-lunarg as he is the one overseeing the Vulkan Loader currently.

**Comment by mark-lunarg** [comment]
This seems to be appropriate place for this PR, as `vk_icd.h` exists here exclusively.  In the future, assigning issues/PRs to others is just fine, and we are happy to help.  Assigning to @lenny-lunarg.

**Pull request merged**
