### PR TITLE
Export CMake Targets File, v2

### PR DESCRIPTION
**Pull request by rbsheth**
Continuation of #112 #110 #89 

This should export useful CMake targets but avoid changes in any downstream projects, since changes are gated on `VULKAN_HEADERS_EXPORT_CMAKE_TARGETS` now.

### CODE REVIEW

**Comment by rahulshethsc** [comment]
@mikew-lunarg PTAL

**Comment by rbsheth** [comment]
*ping* @mikes-lunarg @oddhack

**Comment by mew-cx** [comment]
@rahulshethsc @rbsheth  Sorry, @mikew-lunarg is no longer on this project.

**Comment by neheb** [comment]
Any progress on this?

**Comment by juan-lunarg** [comment]
This PR would help with vcpkg support:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4645

And I imagine other package managers.

**Comment by abouvier** [comment]
In the meantime, CMake (since version 3.21) already provides a [Vulkan find module](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindVulkan.cmake) exporting the imported target `Vulkan::Headers`.
```
find_package(Vulkan 1.3.213)
target_link_libraries(app PRIVATE Vulkan::Headers)
```

**Comment by juan-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-Headers/pull/318

**Pull request closed without merging**
