### PR TITLE
Update CoC link

### PR DESCRIPTION
**Pull request by oddhack**

### CODE REVIEW

**Comment by juan-lunarg** [comment]
image

By changing the extension github doesn't automatically find this file anymore. Not sure if this matters just wanted to point it out.

Also .reuse/dep5 still references the CODE_OF_CONDUCT.md

**Comment by juan-lunarg** [comment]
@oddhack do you mind if I change the code of conduct to use markdown instead?

That way it shows up properly for new contributors (IE when making issues/PRs)

**Comment by oddhack** [comment]
I like using  .adoc consistently, and there's no way of portably imbedding a copyright statement in markdown files AFAIK. We've done this on other Vulkan repos for years w/o  complaints. But I'm not going to fight about it. I will however attempt to file a github bug asking them to properly support this.

**Comment by oddhack** [comment]
It's also possible to insert boilerplate issue / PR templates that guide people to stuff they should know.

**Comment by juan-lunarg** [comment]
> and there's no way of portably imbedding a copyright statement in markdown files AFAIK. 

I recently did this for the markdown files.
https://github.com/KhronosGroup/Vulkan-Headers/commit/85c2334e92e215cce34e8e0ed8b2dce4700f4a50

> BTW, where does that "Community Standards" image you included above come from?

https://github.com/KhronosGroup/Vulkan-Headers/community

> It's also possible to insert boilerplate issue / PR templates that guide people to stuff they should know.

?

**Comment by oddhack** [comment]
https://github.com/KhronosGroup/Vulkan-Headers/issues/templates/edit (I might be wrong about being able to do this for PRs, but def. for issues).

**Pull request merged**
